package com.pojo;
// Generated Jan 20, 2018 5:34:26 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.ManagedBean;




/**
 * Product generated by hbm2java
 */
@ManagedBean
public class Product  implements java.io.Serializable {


     private int pid;
     private String pname;
     private Integer stock;
     private Double unitprice;
     private Double totalprice;

    public Product() {
    }

	
    public Product(int pid) {
        this.pid = pid;
    }
    public Product(int pid, String pname, Integer stock, Double unitprice, Double totalprice) {
       this.pid = pid;
       this.pname = pname;
       this.stock = stock;
       this.unitprice = unitprice;
       this.totalprice = totalprice;
    }
   
    public int getPid() {
        return this.pid;
    }
    
    public void setPid(int pid) {
        this.pid = pid;
    }
    public String getPname() {
        return this.pname;
    }
    
    public void setPname(String pname) {
        this.pname = pname;
    }
    public Integer getStock() {
        return this.stock;
    }
    
    public void setStock(Integer stock) {
        this.stock = stock;
    }
    public Double getUnitprice() {
        return this.unitprice;
    }
    
    public void setUnitprice(Double unitprice) {
        this.unitprice = unitprice;
    }
    public Double getTotalprice() {
        return this.totalprice;
    }
    
    public void setTotalprice(Double totalprice) {
        this.totalprice = totalprice;
    }

   public void doInsert(){
     ProductDAO pr=new ProductDAO();
     pr.doAdd(this); 
   }
   public void doUpdate(){
     ProductDAO pr=new ProductDAO();
     pr.doUp(this); 
   }
   public void doDelete(){
     ProductDAO pr=new ProductDAO();
     pr.doDel(this); 
   }
   private List<Product> showAllProductFromDB= new ArrayList<Product>();

    public List<Product> getShowAllProductFromDB() {
        ProductDAO pr=new ProductDAO();
        showAllProductFromDB=pr.showAllProdut();
        return showAllProductFromDB;
    }

    public void setShowAllProductFromDB(List<Product> showAllProductFromDB) {
        this.showAllProductFromDB = showAllProductFromDB;
    }
    private List<Integer> showAllId = new ArrayList<>();

    public List<Integer> getShowAllId() {
        ProductDAO pr=new ProductDAO();
        showAllId=pr.showAllId();
        return showAllId;
    }

    public void setShowAllId(List<Integer> showAllId) {
        this.showAllId = showAllId;
    }
    public void findaProduct() {
        ProductDAO pr=new ProductDAO();
        Product p = pr.aProduct(pid);
        this.pid = p.pid;
        this.pname = p.pname;
        this.stock = p.stock;
        this.unitprice = p.unitprice;
        this.totalprice=p.totalprice;
    }
    double sum;

    public double getSum() {
        double sum=stock * unitprice;
        return sum;
    }

    public void setSum(double sum) {
        this.sum = sum;
    }
    
    public void doSum(){
        double sum=stock * unitprice;
       System.out.println(sum);
    }
    
}


