package com.pojo;
// Generated Feb 12, 2018 4:35:53 PM by Hibernate Tools 4.3.1

import com.opensymphony.xwork2.ActionSupport;
import javax.faces.bean.ManagedBean;




/**
 * Student generated by hbm2java
 */
@ManagedBean
public class Student extends ActionSupport implements java.io.Serializable {


     private int id;
     private String name;
     private String password;
     
    
     
     public void doInsert() {
        
        StudentDAO lo = new StudentDAO();
        lo.doAdd(this);
        
    }
      @Override
     public String execute(){
         doInsert();
      return SUCCESS;
   }

    public String doShow1() {
        String ret = "error";
        StudentDAO lo = new StudentDAO();
        if (lo.aUser(id, password) != null) {
            ret = "success";
        } else {

            ret = "error";
        }
        return ret;
    }

    public Student() {
    }

	
    public Student(int id) {
        this.id = id;
    }
    public Student(int id, String name, String password) {
       this.id = id;
       this.name = name;
       this.password = password;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


