package com.pojo;
// Generated Jan 21, 2018 4:05:05 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.ManagedBean;

/**
 * Login generated by hbm2java
 */
@ManagedBean
public class Login implements java.io.Serializable {

    private int id;
    private String name;
    private String email;
    private String password;
    private String mobile;

    public Login() {
    }

    public Login(int id) {
        this.id = id;
    }

    public Login(int id, String name, String email, String password, String mobile) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.password = password;
        this.mobile = mobile;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public void doInsert() {
        LoginDAO l = new LoginDAO();
        l.doIns(this);
    }

    public List<Login> show() {
        LoginDAO l = new LoginDAO();
        List<Login> s = l.doShow(this);
        return s;
    }

    public List<Integer> showId() {
        LoginDAO l = new LoginDAO();
        List<Integer> s = l.doShowId(this);
        return s;
    }

    public Login showAllById() {
        LoginDAO l = new LoginDAO();
        Login s=l.ShowById(id);
        this.id=s.id;
        this.name=s.name;
        this.email=s.email;
        this.password=s.password;
        this.mobile=s.mobile;
        return s;
    }

}
